services:
  - type: web
    name: gxvnschatapp
    env: python
    buildCommand: pip install -r server_requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
